### PR TITLE
It it Intended?

### PR DESCRIPTION
**Pull request by groscalin**
While working with RagePixel, just found some weird action in SpriteSheetEditor.

With some RangeAnimations and some SequenceAnimations, Delete Buttons remove Last animation whatever i click.

it's because of this, but if it's intended behavior, that's fine.. :)

### CODE REVIEW

**Comment by JuhaKiili** [comment]
Not intended. This is @JoeOsborn 's code, but seems fine to me. Maybe remove the debug.log ?

**Comment by groscalin** [comment]
sure

**Comment by JoeOsborn** [comment]
It looks good to me. Kind of a boneheaded error! I'm surprised it didn't come up before. If the log gets removed from the pull request, I'll merge it in.

**Comment by ericraue** [comment]
Whoops I had this page open in a browser tab and thought it hadn't been addressed. White space is inconsistent but I don't know how big a deal that is.

**Pull request merged**
